;;;; Auto-generated Lisp loader for fmt bindings
;;;; Generated by clbind-generator v0.1.0
;;;; DO NOT EDIT - regenerate using generate_bindings.py

(defpackage :awesome-fmt
  (:use :common-lisp)
  (:nicknames :awesome-fmt)
  (:documentation "A modern formatting library")
  (:export
   #FORMAT-ERROR
   #SYSTEM-ERROR
   #FORMAT
   #PRINT
   #VFORMAT
   ))

(in-package :awesome-fmt)

(defun load-bindings ()
  "Load the fmt extension bindings."
  ;; The C++ initialization function will be called automatically
  ;; when the extension is loaded by clasp's module system
  (format t "~&Loading fmt bindings...~%"))

;;; Call initialization
(load-bindings)
