;;;; Auto-generated Lisp loader for spdlog bindings
;;;; Generated by clbind-generator v0.1.0
;;;; DO NOT EDIT - regenerate using generate_bindings.py

(defpackage :awesome-spdlog
  (:use :common-lisp)
  (:nicknames :awesome-spdlog)
  (:documentation "Fast C++ logging library")
  (:export
   #LOGGER
   #SINK
   #INFO
   #WARN
   #ERROR
   #DEBUG
   #CRITICAL
   #GET
   #SET-LEVEL
   ))

(in-package :awesome-spdlog)

(defun load-bindings ()
  "Load the spdlog extension bindings."
  ;; The C++ initialization function will be called automatically
  ;; when the extension is loaded by clasp's module system
  (format t "~&Loading spdlog bindings...~%"))

;;; Call initialization
(load-bindings)
