;;;; Auto-generated Lisp loader for json bindings
;;;; Generated by clbind-generator v0.1.0
;;;; DO NOT EDIT - regenerate using generate_bindings.py

(defpackage :awesome-json
  (:use :common-lisp)
  (:nicknames :awesome-json)
  (:documentation "JSON for Modern C++")
  (:export
   #JSON
   #PARSE-ERROR
   #TYPE-ERROR
   #PARSE
   ))

(in-package :awesome-json)

(defun load-bindings ()
  "Load the json extension bindings."
  ;; The C++ initialization function will be called automatically
  ;; when the extension is loaded by clasp's module system
  (format t "~&Loading json bindings...~%"))

;;; Call initialization
(load-bindings)
