/*
 * Auto-generated clbind bindings for spdlog
 * Generated by clbind-generator v0.1.0
 * Source: https://github.com/gabime/spdlog.git
 * Commit: 7c02e204c92545f869e2f04edaab1f19fe8b19fd
 * License: MIT
 * DO NOT EDIT - regenerate using generate_bindings.py
 */

#include <clasp/clbind/clbind.h>

#include <spdlog/spdlog.h>

using namespace clbind;

namespace awesome_spdlog_bindings {

void initialize_spdlog_bindings() {
  package_ pkg("AWESOME-SPDLOG");
  scope_& scope = pkg.scope();

  // Namespace: spdlog
  // Class: spdlog::logger
  class_<spdlog::logger>(scope, "logger")
    .def_constructor<>();  // Default constructor

  // Class: spdlog::sink
  class_<spdlog::sink>(scope, "sink")
    .def_constructor<>();  // Default constructor

  // Function: spdlog::info
  scope.def("info", &spdlog::info);

  // Function: spdlog::warn
  scope.def("warn", &spdlog::warn);

  // Function: spdlog::error
  scope.def("error", &spdlog::error);

  // Function: spdlog::debug
  scope.def("debug", &spdlog::debug);

  // Function: spdlog::critical
  scope.def("critical", &spdlog::critical);

  // Function: spdlog::get
  scope.def("get", &spdlog::get);

  // Function: spdlog::set_level
  scope.def("set_level", &spdlog::set_level);


}

} // namespace
