/*
 * Auto-generated clbind bindings for fmt
 * Generated by clbind-generator v0.1.0
 * Source: https://github.com/fmtlib/fmt.git
 * Commit: e69e5f977d458f2650bb346dadf2ad30c5320281
 * License: MIT
 * DO NOT EDIT - regenerate using generate_bindings.py
 */

#include <clasp/clbind/clbind.h>

#include <fmt/core.h>
#include <fmt/format.h>

using namespace clbind;

namespace awesome_fmt_bindings {

void initialize_fmt_bindings() {
  package_ pkg("AWESOME-FMT");
  scope_& scope = pkg.scope();

  // Namespace: fmt
  // Class: fmt::format_error
  class_<fmt::format_error>(scope, "format_error")
    .def_constructor<>();  // Default constructor

  // Class: fmt::system_error
  class_<fmt::system_error>(scope, "system_error")
    .def_constructor<>();  // Default constructor

  // Function: fmt::format
  scope.def("format", &fmt::format);

  // Function: fmt::print
  scope.def("print", &fmt::print);

  // Function: fmt::vformat
  scope.def("vformat", &fmt::vformat);


}

} // namespace
