/*
 * Auto-generated clbind bindings for json
 * Generated by clbind-generator v0.1.0
 * Source: https://github.com/nlohmann/json.git
 * Commit: 9cca280a4d0ccf0c08f47a99aa71d1b0e52f8d03
 * License: MIT
 * DO NOT EDIT - regenerate using generate_bindings.py
 */

#include <clasp/clbind/clbind.h>

#include <nlohmann/json.hpp>

using namespace clbind;

namespace awesome_json_bindings {

void initialize_json_bindings() {
  package_ pkg("AWESOME-JSON");
  scope_& scope = pkg.scope();

  // Namespace: nlohmann
  // Class: nlohmann::json
  class_<nlohmann::json>(scope, "json")
    .def_constructor<>();  // Default constructor


  // Namespace: nlohmann::json
  // Class: nlohmann::json::parse_error
  class_<nlohmann::json::parse_error>(scope, "parse_error")
    .def_constructor<>();  // Default constructor

  // Class: nlohmann::json::type_error
  class_<nlohmann::json::type_error>(scope, "type_error")
    .def_constructor<>();  // Default constructor

  // Function: nlohmann::json::parse
  scope.def("parse", &nlohmann::json::parse);


}

} // namespace
